version: '3.8'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - node-client-web
      - mysql
      - node-client-fe

  node-client-web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: centrepocket-web
    environment:
      - VIRTUAL_HOST=api.centrepocket.test
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app

  node-client-fe:
    build:
      context: .
      dockerfile: /Users/ufukbozdemir/Documents/workspace/centre-pocket-react-fe/Dockerfile
    working_dir: /usr/src
    container_name: centrepocket-fe
    environment:
      - VIRTUAL_HOST=www.centrepocket.test
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/usr/src

  mysql:
    image: mysql:8.0
    container_name: centrepocket-db
    tty: true
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=centrepocket
      - MYSQL_DATABASE=centrepocket
      - MYSQL_USER=centrepocket
      - MYSQL_PASSWORD=root

volumes:
  mysql:
    driver: local